### ISSUE TITLE
RxLoader always shows CircularProgressIndicator when RxCommand IsBusy

### ISSUE THREAD

**Issue by k2evil** [escamoteur/rx_widgets#11]
Hi. I used `RxLoader` with a `GridView` as child. Because my `GridView` is filled with paginated data from web service and it loads new data everytime it gets to end of the list, I don't want to show `CircularProgressIndicator` whenever I called the API. Also API is called by a `RxCommand`.
The problem is `RxLoader` shows `CircularProgressIndicator` whenever I call the API.
I even tried to set a `Text` widget as the `placeHolderBuilder`. It shows the `Text` for the first call, But then `CircularProgressIndicator` for next calls
```
loadExploreDataCommand = RxCommand.createAsync<void, ExploreResponse>((input) async {
  var newData = await sl
      .get<ExploreServiceStruct>()
      .loadExploreData(input);
  if (response == null) {
    response = newData;
  } else {
    response.data.page = newData.data.page;
    response.data.hasNext = newData.data.hasNext;
    response.data.contents.addAll(newData.data.contents);
  }
  print("Data loaded");
  return response;
});
```
```
class ExplorePageState extends State<ExplorePage>{
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Explore"),
        ),
        body: Column(children: <Widget>[
          Expanded(
            child: RxLoader<ExploreResponse>(
                commandResults:
                sl.get<ExploreManager>().loadExploreDataCommand.results,
                dataBuilder: (context, data) => ExploreGridView(data.data.contents),
                placeHolderBuilder: (context) => Text("hello"),
                errorBuilder: (context, error) => Center(
                  child: Text("Error"),
                )),
          )
        ]));
  }
}
```
I also tried removing the `placeHolderBuilder` and ` placeHolderBuilder: null` but same result everytime.

**Comment by k2evil** [comment]
I just checked the `RxLoader` codes and found out it's not a bug. It's actually the `RxLoader` behavior.
```
var spinner = (platformToUse == TargetPlatform.iOS) ? new CupertinoActivityIndicator(key: widget.spinnerKey, radius: this.widget.radius,) 
                                                        : new CircularProgressIndicator(key: widget.spinnerKey,backgroundColor: widget.backgroundColor,
                                                                                        strokeWidth: widget.strokeWidth,
                                                                                        valueColor: widget.valueColor,
                                                                                        value: widget.value
                                                        ,);

if (lastReceivedItem.isExecuting)
    {
      return new  Center(child: 
                          new Container(width: this.widget.radius * 2, height: this.widget.radius*2, 
                                child: spinner
                              )
                        );
    }
```
But I think it's better to be optional if the `CircularProgressIndicator` is needed to be shown or not... Also if there would be an option to change the `spinner` widget to another widget if it's necessary in app design.

**Comment by escamoteur** [comment]
Hi have you checked RxBuilder instead of rxloader?Another alternative that I often use is not to use any builders but use an RxCommandListener in initState which gives you pretty much control. I m still thinking how you could solve the problem that you only see the spinner the first time by using rx. Am 22.09.2019 15:20 schrieb k2evil <notifications@github.com>:I just checked the RxLoader codes and found out it's not a bug. It's actually the RxLoader behavior.
var spinner = (platformToUse == TargetPlatform.iOS) ? new CupertinoActivityIndicator(key: widget.spinnerKey, radius: this.widget.radius,) 
                                                        : new CircularProgressIndicator(key: widget.spinnerKey,backgroundColor: widget.backgroundColor,
                                                                                        strokeWidth: widget.strokeWidth,
                                                                                        valueColor: widget.valueColor,
                                                                                        value: widget.value
                                                        ,);

if (lastReceivedItem.isExecuting)
    {
      return new  Center(child: 
                          new Container(width: this.widget.radius * 2, height: this.widget.radius*2, 
                                child: spinner
                              )
                        );
    }

But I think it's better to be optional if the CircularProgressIndicator is needed to be shown or not... Also if there would be an option to change the spinner widget to another widget if it's necessary in app design.

**Comment by k2evil** [comment]
> Hi have you checked RxBuilder instead of rxloader?Another alternative that I often use is not to use any builders but use an RxCommandListener in initState which gives you pretty much control. I m still thinking how you could solve the problem that you only see the spinner the first time by using rx. Am 22.09.2019 15:20 schrieb k2evil <notifications@github.com>:I just checked the RxLoader codes and found out it's not a bug. It's actually the RxLoader behavior. var spinner = (platformToUse == TargetPlatform.iOS) ? new CupertinoActivityIndicator(key: widget.spinnerKey, radius: this.widget.radius,) : new CircularProgressIndicator(key: widget.spinnerKey,backgroundColor: widget.backgroundColor, strokeWidth: widget.strokeWidth, valueColor: widget.valueColor, value: widget.value ,); if (lastReceivedItem.isExecuting) { return new Center(child: new Container(width: this.widget.radius * 2, height: this.widget.radius*2, child: spinner ) ); } But I think it's better to be optional if the CircularProgressIndicator is needed to be shown or not... Also if there would be an option to change the spinner widget to another widget if it's necessary in app design. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Hi. `RxCommandBuilder` crashes if you don't set any widget for `busyBuilder`. So it doesn't give you the option of not having a busy spinner neither.
About the other thing, I think it's pretty normal based on the codes. For example I set a `Text` widget for `placeHolderBuilder`. I always see a Text at the beginning of the app, because at the start of the app `!lastReceivedItem.hasData && !lastReceivedItem.hasError`
and if I call the command again, I see a spinner because `lastReceivedItem.isExecuting`.
At first, I didn't know that spinner is inside of the code and I wondered where this comes from

**Comment by escamoteur** [comment]
Just return a SizedBox() from the busyBuilder  when you don't want to display anything. You can make that depending on if its the first time or an update. Am 24.09.2019 11:36 schrieb k2evil <notifications@github.com>:

Hi have you checked RxBuilder instead of rxloader?Another alternative that I often use is not to use any builders but use an RxCommandListener in initState which gives you pretty much control. I m still thinking how you could solve the problem that you only see the spinner the first time by using rx. Am 22.09.2019 15:20 schrieb k2evil notifications@github.com:I just checked the RxLoader codes and found out it's not a bug. It's actually the RxLoader behavior. var spinner = (platformToUse == TargetPlatform.iOS) ? new CupertinoActivityIndicator(key: widget.spinnerKey, radius: this.widget.radius,) : new CircularProgressIndicator(key: widget.spinnerKey,backgroundColor: widget.backgroundColor, strokeWidth: widget.strokeWidth, valueColor: widget.valueColor, value: widget.value ,); if (lastReceivedItem.isExecuting) { return new Center(child: new Container(width: this.widget.radius * 2, height: this.widget.radius*2, child: spinner ) ); } But I think it's better to be optional if the CircularProgressIndicator is needed to be shown or not... Also if there would be an option to change the spinner widget to another widget if it's necessary in app design. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.



Hi. RxCommandBuilder crashes if you don't set any widget for busyBuilder. So it doesn't give you the option of not having a busy spinner neither.

About the other thing, I think it's pretty normal based on the codes. For example I set a Text widget for placeHolderBuilder. I always see a Text at the beginning of the app, because at the start of the app !lastReceivedItem.hasData && !lastReceivedItem.hasError

and if I call the command again, I see a spinner because lastReceivedItem.isExecuting.

At first, I didn't know that spinner is inside of the code and I wondered where this comes from
